update cicd

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -14,7 +14,7 @@ permissions:
   contents: write
 
 jobs:
-  run_model_pipeline:
+  setup_environment:
     runs-on: ubuntu-latest
 
     steps:
@@ -43,6 +43,14 @@ jobs:
 
     - name: Install dependencies
       run: poetry install --no-interaction --no-root
+
+  run_model_pipeline:
+    runs-on: ubuntu-latest
+    needs: setup_environment
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
 
     - name: Set up DVC remote with AWS credentials
       run: |
@@ -93,40 +101,14 @@ jobs:
 
   test:
     runs-on: ubuntu-latest
-    needs: run_model_pipeline
+    needs: [setup_environment, run_model_pipeline]
+
+    outputs:
+      tests_passed: ${{ steps.run-tests.outputs.tests_passed }}
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-
-    - name: Setup Python
-      id: setup-python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.12'
-
-    - name: Install Poetry
-      uses: snok/install-poetry@v1
-      with:
-        virtualenvs-create: true
-        virtualenvs-in-project: true
-        installer-parallel: true
-
-    - name: Load Poetry cache
-      id: load-poetry-cache
-      uses: actions/cache@v3
-      with:
-        path: .venv
-        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
-
-    - name: Install dependencies
-      run: poetry install --no-interaction --no-root
-
-    - name: Set up DVC remote with AWS credentials
-      run: |
-        source .venv/bin/activate
-        dvc remote modify aws_s3 access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-        dvc remote modify aws_s3 secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
     - name: Download artifacts
       uses: actions/download-artifact@v3
@@ -139,6 +121,7 @@ jobs:
       run: |
         source .venv/bin/activate
         pytest tests > pytest_output.txt
+        echo "::set-output name=tests_passed::$(grep -q 'FAILED' pytest_output.txt && echo false || echo true)"
       continue-on-error: true
 
     - name: Save test output
@@ -211,35 +194,12 @@ jobs:
 
   release_model:
     runs-on: ubuntu-latest
-    needs: test
-    if: github.ref == 'refs/heads/main'
+    needs: [setup_environment, test]
+    if: github.ref == 'refs/heads/main' && needs.test.outputs.tests_passed == 'true'
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-
-    - name: Setup Python
-      id: setup-python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.12'
-
-    - name: Install Poetry
-      uses: snok/install-poetry@v1
-      with:
-        virtualenvs-create: true
-        virtualenvs-in-project: true
-        installer-parallel: true
-
-    - name: Load Poetry cache
-      id: load-poetry-cache
-      uses: actions/cache@v3
-      with:
-        path: .venv
-        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
-
-    - name: Install dependencies
-      run: poetry install --no-interaction --no-root
 
     - name: Set up DVC remote with AWS credentials
       run: |
